name: sddemo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  flutter_facebook_login:
  google_sign_in: ^4.5.1
  carousel_slider: ^2.2.1
  flutter_typeahead: ^1.8.7
  page_transition: ^1.1.6

  bottom_navy_bar: ^5.5.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
